### ISSUE TITLE
SecTrustEvaluate [leaf AnchorTrusted]

### ISSUE THREAD

**Issue by jalsco** [nabla-c0d3/ssl-kill-switch2#1]
Hi Alban, 
Am still having same problem that the app crashes immediately after seeing the "SecTrustEvaluate [leaf AnchorTrusted]" message. But only on jb devices. On non-JB devices works no problem.  KillSwitch2 (0.7) has no effect on these symptoms. With killswitch2 removed, I  used your Introspy tool and it shows that the app loads the certificates (from within the bundle) then gives the "SecTrustEvaluate [leaf AnchorTrusted]" message, then crashes. It  does nothing else. It does not crash on non-jb.  I have tried it on 4 different jb devices (including one that is ios8.1) - all show same symptoms. I do not want to hook or modify this app. I do not want to MITM for this app. I just want to run it (exactly as is) on JB device... Any assistance would be greatly appreciated :)

**Comment by nabla-c0d3** [comment]
Hi,
Unfortunately this has nothing to do with SSL Kill Switch. The App crashes most likely because it is detecting the jailbreak, and will crash regardless of whether SSL Kill Switch is installed or not. The "SecTrustEvaluate" message is just an unrelated log message. 

All in all I can't really help you as the solution here is to trick the App into thinking it is running on a non-jailbroken device; this will require some reverse-engineering: looking at the methods names to see if one is called `detectJailbreak` or something, and patching the App to disable the detection mechanism. Closing this issue as it is not about SSL Kill Switch... good luck!
