### ISSUE TITLE
App Store Preference file not found  hook disabled

### ISSUE THREAD

**Issue by CyrusLiu158** [nabla-c0d3/ssl-kill-switch2#14]
v0.10 version in ios 7.1.2 

I have killed itunesstored process , but there is an error in system log:

Apr 22 14:50:13  com.apple.launchd[1] <Notice>: (com.apple.itunesstored) Exited: Killed: 9
Apr 22 14:50:13  itunesstored[1361] <Notice>: MS:Notice: Injecting: com.apple.itunesstored [itunesstored] (847.27)
Apr 22 14:50:14  itunesstored[1361] <Notice>: MS:Notice: Loading: /Library/MobileSubstrate/DynamicLibraries/SSLKillSwitch2.dylib
Apr 22 14:50:14  itunesstored[1361] <Warning>: === SSL Kill Switch 2: Preference file not found.
Apr 22 14:50:14  itunesstored[1361] <Warning>: === SSL Kill Switch 2: Subtrate hook disabled.

**Comment by nabla-c0d3** [comment]
Hi,
To enable SSL Kill Switch you need to comment out line 160 and recompile the tweak:
https://github.com/nabla-c0d3/ssl-kill-switch2/blob/master/SSLKillSwitch/SSLKillSwitch.m#L160

**Comment by rbaulin** [comment]
@CyrusLiu158 , @nabla-c0d3 Looking through the code I found that instead of recompiling the tweak it is easier to put [specific plist](https://gist.github.com/rbaulin/c5aeaefec6718e7992776af7b7c3bdee) with `shouldDisableCertificateValidation` key in `/private/var/mobile/Library/Preferences/com.nablac0d3.SSLKillSwitchSettings.plist` path. Works great with v0.10 from 17 Feb, iOS 8.4 👍

**Comment by moofkit** [comment]
@nabla-c0d3 looks like link is not correct. can you check what exactly need to change to fix this issue?
