### ISSUE TITLE
Doesn't seem to actually function

### ISSUE THREAD

**Issue by chrisbog94** [nabla-c0d3/ssl-kill-switch2#44]
So I get the package installed, the preference pane is showing up with a single toggle, which I enabled.
Testing with Instagram app and iOS 11.0.3.
The settings app crashes a bunch of times before opening properly as well.

**Comment by McFlurriez** [comment]
Yeah, it doesn't work. I tried reaching out on the merged PR but no response. If you look into it, `nw_tls_create_peer_trust` cant simply use the short-circuit for `tls_helper_create_peer_trust`. The former doesnt even call the later in an invalid cert case which is why its not working for iOS 11 but working for iOS 10.

**Comment by nabla-c0d3** [comment]
It works but Instagram is not supported (#39 ).

**Comment by chrisbog94** [comment]
Nabla,

I've tried this with a ton of apps, it's not just related to instagram. Last night I did a clean OS install to 11.0.3 with no luck still. I've tried 7 separate apps all with the same result.

**Comment by McFlurriez** [comment]
Same for me Chris. What's your iOS Major/Minor? Electra Version? List of tested apps?
