### ISSUE TITLE
Add support for iOS 12.0

### ISSUE THREAD

**Issue by iliakukharev** [nabla-c0d3/ssl-kill-switch2#55]

**Comment by iamvinny** [comment]
This tool only works on jailbroken devices and there's no jailbreak for iOS 12.0.

**Comment by SergeKZ** [comment]
RootlessJb ) when support 12 ? please)

**Comment by Tomygames** [comment]
You need a full jailbreak for this tweak to work. Rootless JB isn't a proper jailbreak.

**Comment by iliakukharev** [comment]
https://github.com/pwn20wndstuff/Undecimus/releases/tag/v3.0.0%25b28

I thinks it's time

**Comment by SergeKZ** [comment]
Please rebuild for ios 12 =) thanks

**Comment by nabla-c0d3** [comment]
I tried just now and the latest release doesn't seem to work on iOS 12.

**Comment by qunuan** [comment]
expect support for ios 12 , thanks

**Comment by maris205** [comment]
ios12 jailbreak ok， wait for support

**Comment by SergeKZ** [comment]
> I tried just now and the latest release doesn't seem to work on iOS 12.

will ios 12 support?

**Comment by revilon1991** [comment]
please add ios 12

**Comment by lbbniu** [comment]
please add ios 12

**Comment by Amoystyle** [comment]
> I tried just now and the latest release doesn't seem to work on iOS 12.

It seems that SecTrustSerialize is a trouble！！！

**Comment by Int64x86** [comment]
please add ios 12 support.
root is on almost all devices !!!

**Comment by chenshthu** [comment]
@nabla-c0d3 ,I have set the debug point:"br set -n tls_handshake_set_callbacks",but trust-demo can't run to it.
In order to figure out what had changed in iOS 12’s network stack,I have started by grabbing the dyld shared cache from my iOS 12 device in System/Library/Caches/com.apple.dyld/dyld_shared_cache_arm64，but I don‘t get the CFNetwork!
Please give me suggestions,thx!

**Comment by chenshthu** [comment]
@nabla-c0d3 ,I have set the debug point:"br set -n tls_handshake_set_callbacks",but TrustKit-demo can't run to it.
In order to figure out what had changed in iOS 12’s network stack,I have started by grabbing the dyld shared cache from my iOS 12 device in System/Library/Caches/com.apple.dyld/dyld_shared_cache_arm64，but I don‘t get the CFNetwork!
Please give me suggestions,thx!

**Comment by qunuan** [comment]
please add ios 12 support. thanks

**Comment by Annihil** [comment]
When ETA iOS 12?

**Comment by dnhuan** [comment]
unc0ver is out!

**Comment by trerter** [comment]
Please, rebuild for ios 12
 thanks

**Comment by liuxuan30** [comment]
> @nabla-c0d3 ,I have set the debug point:"br set -n tls_handshake_set_callbacks",but TrustKit-demo can't run to it.
> In order to figure out what had changed in iOS 12’s network stack,I have started by grabbing the dyld shared cache from my iOS 12 device in System/Library/Caches/com.apple.dyld/dyld_shared_cache_arm64，but I don‘t get the CFNetwork!
> Please give me suggestions,thx!

from iOS11 support https://github.com/nabla-c0d3/ssl-kill-switch2/commit/28f05ec052918d3b2c4bfdd9f6b0a7db1a809771

It seems openning "/usr/lib/libnetwork.dylib" rather than shared cache. Try that dylib and see any luck?

**Comment by nabla-c0d3** [comment]
I have released a new version that works on iOS 12; I tested it with the TrustKit demo app: https://github.com/nabla-c0d3/ssl-kill-switch2/releases

**Comment by liuxuan30** [comment]
@nabla-c0d3 you are the best!

**Comment by dnhuan** [comment]
Amazing! Thanks a lot.
