### ISSUE TITLE
not work on IOS 9.0.1 AppStore

### ISSUE THREAD

**Issue by mskmkt0704** [nabla-c0d3/ssl-kill-switch2#8]
i am try download a app,then i input my apple id.it finally failed at the step:connect to gsa.apple.com

itunesstored is restarted and the log show that ssl-kill-switch2 is successful inject to itunesstored 
at:iphone 5s/ios 9.0.1

**Comment by kings0527** [comment]
SSLHandshake: Remote host closed connection during handshake
9.0.2/iphone 6

**Comment by kings0527** [comment]
https://itunes.apple.com/cn/app/99-rockets/id922871241?mt=8
Complete
200 OK
HTTP/1.1
GET
Yes
application/json; target=itml; charset=UTF-8
/192.168.1.105
itunes.apple.com/221.228.64.212


this remote server can capture


but

https://init.itunes.apple.com
Failed
SSLHandshake: Remote host closed connection during handshake
-
HTTP/1.1
CONNECT
No
-
/192.168.1.105
init.itunes.apple.com/221.228.64.212


this server can't.

**Comment by Hope4hope** [comment]
For proxy-ing the App Store things are different; please read the README as it has a link to the instructions. And also, make sure you restart the Apps after having enabled SSL Kill Switch.

The SSL Kill Switch had a MobileLoader filter so that the code disabling certificate validation would only be loaded into apps linking the UIKit bundle (ie. applications with a user interface). This was initially done to restrict the effect of the SSL Kill Switch to App Store apps only. However, itunesstored is a daemon that doesn’t have a user interface, hence the filter prevented MobileLoader from injecting the SSL Kill Switch into the process.

http://iphonedevwiki.net/index.php/MobileSubstrate#MobileLoader

**Comment by nabla-c0d3** [comment]
@Hope4hope can you confirm that it works once you've followed the instructions ? If yes I will close the issue.
Thanks!

**Comment by kings0527** [comment]
my filter bundle is "com.apple.UIKit".

It can work success.

I guess some server of Apple used SSL 3.0 protocol and the server will check client's cert, but the tweak just turn off client's SSL.

Now I complete a tweak to capture AppStore.

You can hook sslread and sslwrite.

**Comment by mskmkt0704** [comment]
i fixed it.i parsed it with IDA.finally i find AuthKit did the real job for login
so add com.apple.AuthKit  to filter bundle,then it worked.

**Comment by nabla-c0d3** [comment]
@mskmkt0704 Nice! I will add AuthKit to the filter then. Thanks!
