### ISSUE TITLE
Not working with unc0ver + iOS 13.3

### ISSUE THREAD

**Issue by karimbenammar** [nabla-c0d3/ssl-kill-switch2#82]
Hi, after the release of unc0ver for A9-A11 iOS 13.3, ssl killswitch 2 is crashing springboard whenever installed.

**Comment by fboas** [comment]
Same for me here

**Comment by SergeKZ** [comment]
Yes, not work =(  iphone 7  unc0ver   iOS 13.3

**Comment by l0gg3r** [comment]
that's because "Cydia substrate" is not available for unc0ver

**Comment by SergeKZ** [comment]
Please update for  substitute

**Comment by Itaybre** [comment]
I made a PR with support for A12/A13 that only have JB with Substitute.
I should be simple to add this when substitute is used, give me some hours to update it

**Comment by mileyvirus** [comment]
Hey @Itaybre I compiled your code but it just crashes any app I open, does it work on your end? I have an iPhone 11 Pro Max with iOS 13.3 with the latest unc0ver.

**Comment by Itaybre** [comment]
@mileyvirus it is working on my iPhone 11 Pro 13.3
I try adding the fix to all the hooks, I only added to the one crashing my device

**Comment by puuurp** [comment]
@Itaybre is there anyway that you could update the master with the new code or create a new topic for the substitute version? I don't know what to do with the code you have in PR

**Comment by blunden** [comment]
@Itaybre Did you ever end up applying your fix to the other hooks?

**Comment by jankais3r** [comment]
Fully working version for Unc0ver is now available here: https://github.com/julioverne/ssl-kill-switch2

**Comment by blunden** [comment]
> Fully working version for Unc0ver is now available here: https://github.com/julioverne/ssl-kill-switch2

Interesting. 😀 Why did you remove the license, readme etc. though?

**Comment by jankais3r** [comment]
It is not my repository. I made a bounty for it on Reddit and julioverne was kind enough to pick up the challenge. Also, judging by the code, it seems to be an update of the [original SSL Kill Switch](https://github.com/iSECPartners/ios-ssl-kill-switch), rather than SSL Kill Switch 2. Yes it’s missing a license, but the original authors are credited in the Cydia repo.

![DFDC585A-AED3-44B3-AA19-798B46EB1162](https://user-images.githubusercontent.com/2159464/83941386-336a9e80-a7eb-11ea-80f6-06532439555e.jpeg)

**Comment by blunden** [comment]
I see. It definitely contains code from here too though so he probably removed any code that doesn't apply to iOS and removed the Xcode project.

It would've been preferable if he had made a smaller diff that could be submitted as a pull request here since I don't expect him to maintain his fork in the future.

**Comment by BreakfastSerial** [comment]
> Fully working version for Unc0ver is now available here: https://github.com/julioverne/ssl-kill-switch2

Is there a built .deb or a cydia repo that hosts this? Thank you and stay safe.

Never mind. I'm serially blind. If anyone has the same issue: https://julioverne.github.io/

**edit:** For me this crashes multiple apps once active (including my target app, the general system settings, filza and others) (iOS 13.2.2)
