### ISSUE TITLE
Not working for iOS 13.3 with Substitute

### ISSUE THREAD

**Issue by GrumpyMonkey3** [nabla-c0d3/ssl-kill-switch2#86]
My previous issue was closed because I was "complaining" about this getting fixed. Alright you lazy ¢unt. Not my fault you made a product that only works on older devices and that you're too lazy to update it. Instead of sitting on here, you should be working on updating. I was just informing you that this doesn't work for the newest jailbreak and you got salty :kek: You definitely got bullied in school. People like you do free work for people like me, and that's just how the world works buddy.

**Comment by GrumpyMonkey3** [comment]
I even said please 🤦🏻‍♂️ Like yea bro I'm definitely complaining. You're braindead as hell

**Comment by GrumpyMonkey3** [comment]
![4EF5D081-3C78-4223-BCF1-BD37CE72B13C](https://user-images.githubusercontent.com/62360358/77130205-418ef700-6a14-11ea-9067-1855c77e76c8.png)

**Comment by nabla-c0d3** [comment]
There is already a ticket for this issue specifically, and you replied on it: https://github.com/nabla-c0d3/ssl-kill-switch2/issues/82 and then opened yet another ticket for the exact same thing.
I closed your new ticket because it was just a duplicate with you complaining about why the issue had not been resolved yet. Opening more tickets doesn't help either.
